name: test3
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  http: ^1.3.0
  fl_chart: ^0.70.2
  flutter_data: ^2.0.0
  json_annotation: ^4.9.0
  provider: ^6.1.2
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  file_picker: ^9.0.0

  firebase_core: ^3.12.0
  firebase_storage: ^12.4.3
  flutter_dotenv: ^5.2.1

dev_dependencies:
  json_serializable: ^6.9.4
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
